apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-http-server
  labels:
    app: python-http-server
spec:
  selector:
    matchLabels:
      app: python-http-server
  template:
    metadata:
      labels:
        app: python-http-server
    spec:
      containers:
      - name: python-http-server
        image: willbennett/python-http-server
        ports:
        - name: http-port
          containerPort: 9000
